/**************************************************************************
 *                                                                        *
 *               Copyright (C) 1997, Dynamix, Inc.                        *
 *                                                                        *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Dynamix, Inc.,  and are      *
 *  protected by Federal copyright  law.  They  may not be disclosed to   *
 *  third parties  or copied or duplicated in any form, in whole or       *
 *  in part, without the prior written consent of Dynamix, Inc.           *
 *                                                                        *
 *************************************************************************/

#define DMA_QUEUE_SIZE  50
#define NUM_PI_MSGS     8

#define TID_IDLE        1
#define PRI_IDLE        10

#define TID_MAINPROC    3
#define PRI_MAINPROC    10

#define TID_SOUND_ID    5
#define PRI_SOUND       3

#define	STACKSIZE	0x10000

