/*****************************************************************************
* @project N64 Music Teacher
* @info The game for learning music.
* @platform Nintendo 64
* @autor Valery P. (https://github.com/hww)
*****************************************************************************/

#define DMA_QUEUE_SIZE  50
#define NUM_PI_MSGS     8

#define TID_IDLE        1
#define PRI_IDLE        10

#define TID_MAINPROC    3
#define PRI_MAINPROC    10

#define TID_SOUND_ID    5
#define PRI_SOUND       3

#define	STACKSIZE       0x10000

