/*****************************************************************************
* @project N64 Music Teacher
* @info The game for learning music.
* @platform Nintendo 64
* @autor Valery P. (https://github.com/hww)
*****************************************************************************/

/* these are the static display lists */

extern Gfx      init_dl[];
extern Gfx      clearcfb_dl[];
extern Gfx      clearzbuffer_dl[];

